dist: trusty

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - docker

  
addons:
apt:
  packages:
    - docker-ce
  
sudo: required
language: java
jdk:
  - openjdk8
  
before_install:
# Might have to sed the config files twice to start up catalog
  - docker ps
  - sudo chmod 777 /etc/hosts
  - echo -e '127.0.0.1 nginx\n' >> /etc/hosts
  - echo -e '127.0.0.1 ci-mongo\n' >> /etc/hosts
  - cat /etc/hosts
  - sudo mkdir -p /mnt/condor; sudo chmod 777 /mnt/condor;
  - sudo apt-get -qq update
  - git clone https://github.com/bio-boris/mini_kb.git && cd mini_kb && git checkout justExecutionEngine
  - time docker-compose -f execution-engine.yml pull
  - time docker-compose -f execution-engine.yml up -d
  - echo "Waiting for mini_kb to start"
  - sleep 540
  - curl -k -m 5 https://nginx/services/njs 
  - curl -k -m 5 https://nginx/services/auth
  - curl -k -m 5 https://nginx/services/catalog 
  - docker-compose -f execution-engine.yml logs njs
  - docker-compose -f execution-engine.yml logs auth
  - docker-compose -f execution-engine.yml logs catalog



# install:
#   - sudo rm -rf /usr/bin/mongod; sudo rm -rf /usr/bin/mongo
#   - cd $HOME/mongodb/; wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.6.tgz
#   - tar xzf mongodb-linux-x86_64-3.6.6.tgz
#   - ${PWD}/mongodb-linux-x86_64-3.6.6/bin/mongod --version
#   - sudo ln -s  ${PWD}/mongodb-linux-x86_64-3.6.6/bin/mongod /usr/bin/mongod
#   - sudo ln -s ${PWD}/mongodb-linux-x86_64-3.6.6/bin/mongo /usr/bin/mongo 
  
env:
  global: # The following are for the dockerhub DOCKER_USER and DOCKER_PASS env vars used in the push script
    - secure: "GEbQy4zR5hhHDzjoThGyCHZVmpEWKduwR/sZ1sR8csOYrfYqQTHinhAMY+KAdUhjJfWGwR9l2v2xkhyokzdADhKOqZJo7jkkioPEtENdocTWMYq7Qedg6kUCzcAutURIBCcoJtW4vrpGZ+1YR4vB8BhA11KA62QUbsQY3ds/LTg="
    - secure: "NbHt1OUyrTXmN+tYAFcGH3mxlxraDKJ6WQNTJTG+u+wTOzh2MU1bf59l+oanvqlydpd7ZzG7c2cUpje5hvBMEV9s9jwdWqTlGXHWpcU3a1wZdNOkkAPK0Cb3opabRLwIqjovaoAAouSJCq/jUADzhusjrZcn5JVA7sSpYyJT3uE="
script:
  - whoami
  - cd ~/build/kbase/njs_wrapper/
  - cp dev_tools/test.cfg.example test.cfg
  - cp dev_tools/deploy_local_minikb.cfg deploy.cfg

  # PASSING
  # - ./gradlew test --tests TestAlpineDeleteRunner --info 
  # - ./gradlew test --tests DockerTest PASSING
  # - ./gradlew test --tests ExecEngineMongoDbTest --info --scan
  # WIP
  - ./gradlew test --tests CondorIntegrationTest --info --scan
  
  
#   - make build-docker-image
after_success:
  - IMAGE_NAME=kbase/kb_njs_wrapper ./build/push2dockerhub.sh
